name: Chatterbox
main: org.royaldev.chatterbox.Chatterbox
version: ${pluginversion}
authors: [jkcclemens, gdude2002]
description:  Simple, elegant, powerful. Minecraft chat as it was supposed to be.

reflectcommands:
- commands.impl.Whatever
