name: Chatterbox
main: org.royaldev.chatterbox.Chatterbox
version: ${pluginversion}
authors: [jkcclemens, gdude2002]
# TODO: How do we determine softdepends for loading in dependencies? Load them in after server start using a task?
description: Do chat things. # TODO: Change

reflectcommands:
- commands.impl.Whatever
